// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sensor.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sensor_Watch_FullMethodName = "/example.Sensor/Watch"
)

// SensorClient is the client API for Sensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorClient interface {
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, WatchResponse], error)
}

type sensorClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorClient(cc grpc.ClientConnInterface) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sensor_ServiceDesc.Streams[0], Sensor_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sensor_WatchClient = grpc.BidiStreamingClient[WatchRequest, WatchResponse]

// SensorServer is the server API for Sensor service.
// All implementations must embed UnimplementedSensorServer
// for forward compatibility.
type SensorServer interface {
	Watch(grpc.BidiStreamingServer[WatchRequest, WatchResponse]) error
	mustEmbedUnimplementedSensorServer()
}

// UnimplementedSensorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorServer struct{}

func (UnimplementedSensorServer) Watch(grpc.BidiStreamingServer[WatchRequest, WatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSensorServer) mustEmbedUnimplementedSensorServer() {}
func (UnimplementedSensorServer) testEmbeddedByValue()                {}

// UnsafeSensorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServer will
// result in compilation errors.
type UnsafeSensorServer interface {
	mustEmbedUnimplementedSensorServer()
}

func RegisterSensorServer(s grpc.ServiceRegistrar, srv SensorServer) {
	// If the following call pancis, it indicates UnimplementedSensorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sensor_ServiceDesc, srv)
}

func _Sensor_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServer).Watch(&grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sensor_WatchServer = grpc.BidiStreamingServer[WatchRequest, WatchResponse]

// Sensor_ServiceDesc is the grpc.ServiceDesc for Sensor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sensor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Sensor_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sensor.proto",
}
